modLoader="javafml"
loaderVersion="[4,)"

license="BSD-3-Clause"

issueTrackerURL="https://gitlab.com/antarcticgardens/fauna_mail/-/issues"

[[mods]]
modId="${modId}"
version="${modVersion}"
displayName="Mara"

displayURL="https://antarcticgardens.org/"

#logoFile="examplemod.png" #optional

authors="Antarctic Gardens"

description='''

'''

#[[mixins]]
#config="${modId}.mixins.json"

[[dependencies.${modId}]]
modId="neoforge"
type="required"
versionRange="[21.0.0-beta,)"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="minecraft"
type="required"
versionRange="[1.21,1.21.1)"
ordering="NONE"
side="BOTH"
